set(var_1 TRUE)
if(var_1)
    message("var_1 is true")
else()
    message("var_1 is false")
endif()

set(var_2)
if(var_2)
    message("var_2 is true")
else()
    message("var_2 is false")
endif()

set(var_3 "hello world!")
if(var_3)
    message("var_3 is true")
else()
    message("var_3 is false")
endif()

#set(var_4 "hello world!")
if(var_4)
    message("var_4 is true")
else()
    message("var_4 is false")
endif()

set(var_1 OFF)
set(var_2 "var_1")
if(${var_2})
    message("var_2 is true")
else()
    message("var_2 is false")
endif()

set(var_1 ON)
set(var_2 "var_1")
if(${var_2})
    message("var_2 is true")
else()
    message("var_2 is false")
endif()

if(1 EQUAL 2)
    message("1 EQUAL 2")
else()
    message("1 NOT EQUAL 2")
endif()

if(1 LESS 2)
    message("1 LESS 2")
else()
    message("1 NOT LESS 2")
endif()